### ISSUE TITLE
Would you guys implement NFTs living 1:1 inside blockchain that scale, it is not only a dream

### ISSUE THREAD

**Issue by vipertechofficial** [bybit-exchange/QuickStartWithPostman#20]
Hello,

I have a tools that use a protocol for pixel art, the old video games had the need to find their bitmap images remastered the impersonal way they created up-scaling algorithms working very great. I build a tool, I need sponsors.

![SCREENSHOTS_GRID_pngquant](https://user-images.githubusercontent.com/74778466/197511551-7bee05ba-af62-4370-9c39-35ac0600cdcd.png)
[Pixelarts_NFTs_PixaPics_Light.pdf](https://github.com/bybit-exchange/QuickStartWithPostman/files/9851119/Pixelarts_NFTs_PixaPics_Light.pdf)

**Comment by vipertechofficial** [comment]
## SDK for up-scaling images

```js
import Pixa from "xxx-pixa-pics-upscale"; // Soon ready
import xbrz from "xxx-pixa-pics-upscale/xbrz"; // Soon online

var pixa = new Pixa();
pixa.add(xbrz)
pixa.upscale(base64, "xbrz").then(function(base642nd){

    //img.src = base642nd;
});
```

**Comment by vipertechofficial** [comment]
@sangechen Does the concept of 1:1 stored NFTs speaks to you?

**Comment by vipertechofficial** [comment]
@dextertd Does the concept of 1:1 stored NFTs speaks to you?

**Comment by dextertd** [comment]
@vipertechofficial This is not the appropriate place to have this discussion.

**Comment by vipertechofficial** [comment]
@dextertd where is the place it is appropriate?
